import Head from 'next/head'
import Image from 'next/image'
import { Container } from 'react-bootstrap'
import styles from '../assets/styles/Home.module.css'
import Quiz from './quiz'


export default function Home() {
  return (
    <>
      <Head>
        <title>Quiz App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <section className='p-3'>
      <Container>
      <Quiz></Quiz>
      </Container>
    </section>
     
    </>
  )
}
