import Head from 'next/head'
import Image from 'next/image'
import { Container } from 'react-bootstrap'
import styles from '../assets/styles/Home.module.css'
import Quiz from './quiz'


export default function Home() {
  return (
    <div className="bg-light">
      <Head>
        <title>Quiz App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <section>
      <Container>
      <Quiz></Quiz>
      </Container>
    </section>
     
    </div>
  )
}
